## DECATHLON 2

In this notebook I am processing the different dataframes to have all the data included in one dataframe.

In [1]:
import pandas as pd 
pd.set_option('display.max_columns', 500)

In [2]:
# open datasets 
recomendations = pd.read_csv('recomendations_train_IT.csv')
recomendations.head(3)

,reco_id,time_reco,id_sender,id_reciever,id_product,product_bought
0,5dc916dc-6fa3-488f-8ad2-fd14100fa113,2008-02-09 17:58:24,5565ac1e-4c2a-4fd8-b990-7a11d594dc0e,13a6c635-2f20-4e22-9e76-c3761d1111be,8605674,1
1,e9b6a2bb-58d4-4e62-8fda-239da00e42a1,1995-06-17 04:27:17,4c1e438a-2b8c-4f84-a22a-869eea346661,84f27bd9-0d26-4f84-b585-cca0e4bbd1d5,8603017,1
2,91a31be2-e71f-436a-917e-1ac65cc9ef2e,2002-04-10 19:26:53,51c3fb8f-c26f-4808-a69a-3f728256cf7a,8c333f9b-af38-4a0c-8bdc-428ffa061312,8763489,1

In [3]:
products = pd.read_csv('prods_IT.csv')
products.head(3)

,modeild,weblabel,brand,catchline,productnature,family,Review-AverageRating,DisplayPrice-Amount,ListPrice-Amount
0,8071204,REGULADOR DE RED DE TENIS,ARTENGO,Indispensable para una buena altura de red.,REDES,EQUIPAMIENTO COACH/CLUB,5.0,9.99,9.99
1,8071566,PELOTA DE TENIS POLIVALENTE TB920 *4 AMARILLO,ARTENGO,¡Durabilidad y control!Pelota oficial del torn...,Pelota de tenis,PELOTAS TENIS,4.5,5.99,5.99
2,8071569,PELOTA DE TENIS TB530 *4 AMARILLO,ARTENGO,¡Pelota de competición a bajo precio!Nuevo emp...,Pelota de tenis,PELOTAS TENIS,4.5,4.49,4.49

In [4]:
users = pd.read_csv('users_IT.csv')
users.head(3)

,person_id,complete_name,age,address
0,d0eb7350-ce10-42a2-bab1-cb66319bdfa6,Leah Wright,26,"5942 Phillip Ridge\nWest Hannah, WA 76733"
1,06ada2a9-ec6e-4306-b83b-33af4489fca0,Jonathan Hill,26,"390 Shelley Ways\nBoydburgh, NY 48020"
2,acf71426-adca-4f48-87d6-4978dc538448,Anne Dougherty,28,USCGC Thompson\nFPO AE 51140

In [5]:
recomendations["year"]=recomendations['time_reco'].astype(str).str[:4]
recomendations["month"]=recomendations['time_reco'].astype(str).str[8:10]

recomendations["year"]= recomendations["year"].astype(int)
recomendations["month"]=recomendations["month"].astype(int)
recomendations = recomendations.drop(columns=["time_reco"])
recomendations

,reco_id,id_sender,id_reciever,id_product,product_bought,year,month
0,5dc916dc-6fa3-488f-8ad2-fd14100fa113,5565ac1e-4c2a-4fd8-b990-7a11d594dc0e,13a6c635-2f20-4e22-9e76-c3761d1111be,8605674,1,2008,9
1,e9b6a2bb-58d4-4e62-8fda-239da00e42a1,4c1e438a-2b8c-4f84-a22a-869eea346661,84f27bd9-0d26-4f84-b585-cca0e4bbd1d5,8603017,1,1995,17
2,91a31be2-e71f-436a-917e-1ac65cc9ef2e,51c3fb8f-c26f-4808-a69a-3f728256cf7a,8c333f9b-af38-4a0c-8bdc-428ffa061312,8763489,1,2002,10
3,b69901f9-c70b-4133-be43-cc6116f1c8fd,45e9a922-e602-4e8f-be77-d6486779ae0f,5f9dfbb7-8bca-494a-802e-f11f12c9906a,8607307,1,2015,31
4,0ccdd3e7-a1cb-43fd-814d-a501278c9f9c,250343f4-b757-4c3f-aaea-d7d3ddb14744,34d40a00-18f9-4fa5-9973-ffd5d8663c6f,8372995,1,2001,6
...,...,...,...,...,...,...,...
6995,b15fcb43-75a5-4a7a-904e-1707686d57a1,e3d1e9ab-01fb-4ade-ae58-8449f8fbe742,6d1012bc-d57d-4095-87f9-8ef9767987d5,8561587,0,1991,12
6996,4b5d39cf-2b39-4b84-8052-d94b14193f69,807a90a6-3103-4cef-944a-304a663b58e1,30edad71-d3f3-479f-87ad-f093880ccf80,8667378,1,2004,21
6997,50349b56-4dbe-4da4-8145-4abd1f485b94,81bf0b99-99aa-4211-92be-2315810ee347,cc410d52-c17b-4b93-b07e-e217a75738c6,8487421,1,1977,2
6998,11c4e42c-048b-454f-9dba-8943234fb752,8e2cb852-2d27-4a31-8c63-349f9061e641,0c504bb9-49a6-4676-978c-95364a3f06e5,8752744,0,1986,17
6999,f374b7cd-1b1e-4953-87b7-dbb9737b111e,da4136bf-e92d-4d25-9f3f-64bd4f833aab,f38fceab-26bc-4470-b68a-ee5e67cc540d,8648004,1,2011,11

In [6]:
products = products.rename(columns = {'modeild' : 'id_product'})

In [7]:
recom_prod = recomendations.merge(products.drop_duplicates('id_product'), on = 'id_product', how= 'left')
recom_prod.head()

,reco_id,id_sender,id_reciever,id_product,product_bought,year,month,weblabel,brand,catchline,productnature,family,Review-AverageRating,DisplayPrice-Amount,ListPrice-Amount
0,5dc916dc-6fa3-488f-8ad2-fd14100fa113,5565ac1e-4c2a-4fd8-b990-7a11d594dc0e,13a6c635-2f20-4e22-9e76-c3761d1111be,8605674,1,2008,9,Zapatillas Squash Salming Viper 5 Hombre Amari...,SALMING,"La Viper es una zapatilla rápida, flexible y d...",ZAPATILLAS,ZAPATILLA SQUASH,5.0,79.99,99.99
1,e9b6a2bb-58d4-4e62-8fda-239da00e42a1,4c1e438a-2b8c-4f84-a22a-869eea346661,84f27bd9-0d26-4f84-b585-cca0e4bbd1d5,8603017,1,1995,17,Camiseta de bádminton manga corta Mujer Perfly...,PERFLY,Primera camiseta por precio pensada para el bá...,CAMISETAS MANGA CORTA,Ropa badminton mujer,4.6,9.99,9.99
2,91a31be2-e71f-436a-917e-1ac65cc9ef2e,51c3fb8f-c26f-4808-a69a-3f728256cf7a,8c333f9b-af38-4a0c-8bdc-428ffa061312,8763489,1,2002,10,Zapatillas tenis Hombre Revolt Pro 4.0 Negro A...,HEAD,Estas zapatillas de tenis HEAD REVOLT PRO 4.0 ...,ZAPATILLAS,CALZADO HOMBRE MULTICANCHA EXPERTO,5.0,124.99,124.99
3,b69901f9-c70b-4133-be43-cc6116f1c8fd,45e9a922-e602-4e8f-be77-d6486779ae0f,5f9dfbb7-8bca-494a-802e-f11f12c9906a,8607307,1,2015,31,Zapatillas de pádel Mujer Kuikma PS 990 Dynami...,KUIKMA,Estas zapatillas de pádel te aportarán el dina...,ZAPATILLAS,CALZADO PADEL,4.4,64.99,64.99
4,0ccdd3e7-a1cb-43fd-814d-a501278c9f9c,250343f4-b757-4c3f-aaea-d7d3ddb14744,34d40a00-18f9-4fa5-9973-ffd5d8663c6f,8372995,1,2001,6,Zapatillas de tenis Mujer TS 100 blanco,ARTENGO,Zapatillas de tenis concebidas para dar los pr...,ZAPATILLAS,CALZADO MUJER MULTICANCHA INIC/PERFECC,4.5,12.99,12.99

In [8]:
recomendations

,reco_id,id_sender,id_reciever,id_product,product_bought,year,month
0,5dc916dc-6fa3-488f-8ad2-fd14100fa113,5565ac1e-4c2a-4fd8-b990-7a11d594dc0e,13a6c635-2f20-4e22-9e76-c3761d1111be,8605674,1,2008,9
1,e9b6a2bb-58d4-4e62-8fda-239da00e42a1,4c1e438a-2b8c-4f84-a22a-869eea346661,84f27bd9-0d26-4f84-b585-cca0e4bbd1d5,8603017,1,1995,17
2,91a31be2-e71f-436a-917e-1ac65cc9ef2e,51c3fb8f-c26f-4808-a69a-3f728256cf7a,8c333f9b-af38-4a0c-8bdc-428ffa061312,8763489,1,2002,10
3,b69901f9-c70b-4133-be43-cc6116f1c8fd,45e9a922-e602-4e8f-be77-d6486779ae0f,5f9dfbb7-8bca-494a-802e-f11f12c9906a,8607307,1,2015,31
4,0ccdd3e7-a1cb-43fd-814d-a501278c9f9c,250343f4-b757-4c3f-aaea-d7d3ddb14744,34d40a00-18f9-4fa5-9973-ffd5d8663c6f,8372995,1,2001,6
...,...,...,...,...,...,...,...
6995,b15fcb43-75a5-4a7a-904e-1707686d57a1,e3d1e9ab-01fb-4ade-ae58-8449f8fbe742,6d1012bc-d57d-4095-87f9-8ef9767987d5,8561587,0,1991,12
6996,4b5d39cf-2b39-4b84-8052-d94b14193f69,807a90a6-3103-4cef-944a-304a663b58e1,30edad71-d3f3-479f-87ad-f093880ccf80,8667378,1,2004,21
6997,50349b56-4dbe-4da4-8145-4abd1f485b94,81bf0b99-99aa-4211-92be-2315810ee347,cc410d52-c17b-4b93-b07e-e217a75738c6,8487421,1,1977,2
6998,11c4e42c-048b-454f-9dba-8943234fb752,8e2cb852-2d27-4a31-8c63-349f9061e641,0c504bb9-49a6-4676-978c-95364a3f06e5,8752744,0,1986,17
6999,f374b7cd-1b1e-4953-87b7-dbb9737b111e,da4136bf-e92d-4d25-9f3f-64bd4f833aab,f38fceab-26bc-4470-b68a-ee5e67cc540d,8648004,1,2011,11

In [9]:
recom_prod.shape

(7000, 15)

In [10]:
recom_prod.shape

(7000, 15)

In [11]:
recom_prod.head()

,reco_id,id_sender,id_reciever,id_product,product_bought,year,month,weblabel,brand,catchline,productnature,family,Review-AverageRating,DisplayPrice-Amount,ListPrice-Amount
0,5dc916dc-6fa3-488f-8ad2-fd14100fa113,5565ac1e-4c2a-4fd8-b990-7a11d594dc0e,13a6c635-2f20-4e22-9e76-c3761d1111be,8605674,1,2008,9,Zapatillas Squash Salming Viper 5 Hombre Amari...,SALMING,"La Viper es una zapatilla rápida, flexible y d...",ZAPATILLAS,ZAPATILLA SQUASH,5.0,79.99,99.99
1,e9b6a2bb-58d4-4e62-8fda-239da00e42a1,4c1e438a-2b8c-4f84-a22a-869eea346661,84f27bd9-0d26-4f84-b585-cca0e4bbd1d5,8603017,1,1995,17,Camiseta de bádminton manga corta Mujer Perfly...,PERFLY,Primera camiseta por precio pensada para el bá...,CAMISETAS MANGA CORTA,Ropa badminton mujer,4.6,9.99,9.99
2,91a31be2-e71f-436a-917e-1ac65cc9ef2e,51c3fb8f-c26f-4808-a69a-3f728256cf7a,8c333f9b-af38-4a0c-8bdc-428ffa061312,8763489,1,2002,10,Zapatillas tenis Hombre Revolt Pro 4.0 Negro A...,HEAD,Estas zapatillas de tenis HEAD REVOLT PRO 4.0 ...,ZAPATILLAS,CALZADO HOMBRE MULTICANCHA EXPERTO,5.0,124.99,124.99
3,b69901f9-c70b-4133-be43-cc6116f1c8fd,45e9a922-e602-4e8f-be77-d6486779ae0f,5f9dfbb7-8bca-494a-802e-f11f12c9906a,8607307,1,2015,31,Zapatillas de pádel Mujer Kuikma PS 990 Dynami...,KUIKMA,Estas zapatillas de pádel te aportarán el dina...,ZAPATILLAS,CALZADO PADEL,4.4,64.99,64.99
4,0ccdd3e7-a1cb-43fd-814d-a501278c9f9c,250343f4-b757-4c3f-aaea-d7d3ddb14744,34d40a00-18f9-4fa5-9973-ffd5d8663c6f,8372995,1,2001,6,Zapatillas de tenis Mujer TS 100 blanco,ARTENGO,Zapatillas de tenis concebidas para dar los pr...,ZAPATILLAS,CALZADO MUJER MULTICANCHA INIC/PERFECC,4.5,12.99,12.99

In [12]:
recom_prod['precio_dif'] = (recom_prod['DisplayPrice-Amount'] - recom_prod['ListPrice-Amount']) != 0
recom_prod.shape

(7000, 16)

In [13]:
recom_prod.head()

,reco_id,id_sender,id_reciever,id_product,product_bought,year,month,weblabel,brand,catchline,productnature,family,Review-AverageRating,DisplayPrice-Amount,ListPrice-Amount,precio_dif
0,5dc916dc-6fa3-488f-8ad2-fd14100fa113,5565ac1e-4c2a-4fd8-b990-7a11d594dc0e,13a6c635-2f20-4e22-9e76-c3761d1111be,8605674,1,2008,9,Zapatillas Squash Salming Viper 5 Hombre Amari...,SALMING,"La Viper es una zapatilla rápida, flexible y d...",ZAPATILLAS,ZAPATILLA SQUASH,5.0,79.99,99.99,True
1,e9b6a2bb-58d4-4e62-8fda-239da00e42a1,4c1e438a-2b8c-4f84-a22a-869eea346661,84f27bd9-0d26-4f84-b585-cca0e4bbd1d5,8603017,1,1995,17,Camiseta de bádminton manga corta Mujer Perfly...,PERFLY,Primera camiseta por precio pensada para el bá...,CAMISETAS MANGA CORTA,Ropa badminton mujer,4.6,9.99,9.99,False
2,91a31be2-e71f-436a-917e-1ac65cc9ef2e,51c3fb8f-c26f-4808-a69a-3f728256cf7a,8c333f9b-af38-4a0c-8bdc-428ffa061312,8763489,1,2002,10,Zapatillas tenis Hombre Revolt Pro 4.0 Negro A...,HEAD,Estas zapatillas de tenis HEAD REVOLT PRO 4.0 ...,ZAPATILLAS,CALZADO HOMBRE MULTICANCHA EXPERTO,5.0,124.99,124.99,False
3,b69901f9-c70b-4133-be43-cc6116f1c8fd,45e9a922-e602-4e8f-be77-d6486779ae0f,5f9dfbb7-8bca-494a-802e-f11f12c9906a,8607307,1,2015,31,Zapatillas de pádel Mujer Kuikma PS 990 Dynami...,KUIKMA,Estas zapatillas de pádel te aportarán el dina...,ZAPATILLAS,CALZADO PADEL,4.4,64.99,64.99,False
4,0ccdd3e7-a1cb-43fd-814d-a501278c9f9c,250343f4-b757-4c3f-aaea-d7d3ddb14744,34d40a00-18f9-4fa5-9973-ffd5d8663c6f,8372995,1,2001,6,Zapatillas de tenis Mujer TS 100 blanco,ARTENGO,Zapatillas de tenis concebidas para dar los pr...,ZAPATILLAS,CALZADO MUJER MULTICANCHA INIC/PERFECC,4.5,12.99,12.99,False

In [14]:
# recom_prod.to_csv('recomendation_products2.csv', index= False)

In [15]:
recom_prod.shape

(7000, 16)

In [16]:
users.head()

,person_id,complete_name,age,address
0,d0eb7350-ce10-42a2-bab1-cb66319bdfa6,Leah Wright,26,"5942 Phillip Ridge\nWest Hannah, WA 76733"
1,06ada2a9-ec6e-4306-b83b-33af4489fca0,Jonathan Hill,26,"390 Shelley Ways\nBoydburgh, NY 48020"
2,acf71426-adca-4f48-87d6-4978dc538448,Anne Dougherty,28,USCGC Thompson\nFPO AE 51140
3,07017851-e9cc-40d2-a0f3-e82819761e72,Lydia Hall,41,"5511 Miller Dam\nWest Michael, UT 03004"
4,d116bb8a-43df-42a5-9575-5af33e088ec9,Brianna Washington,28,"70072 John Keys\nNew Amandaport, OH 85289"

In [17]:
users["zip"]=users['address'].astype(str).str[-5:]
users["state"]=users['address'].astype(str).str[-8:-6]


users= users.drop(columns=["complete_name","address"])
users

                                person_id  age    zip state
0    d0eb7350-ce10-42a2-bab1-cb66319bdfa6   26  76733    WA
1    06ada2a9-ec6e-4306-b83b-33af4489fca0   26  48020    NY
2    acf71426-adca-4f48-87d6-4978dc538448   28  51140    AE
3    07017851-e9cc-40d2-a0f3-e82819761e72   41  03004    UT
4    d116bb8a-43df-42a5-9575-5af33e088ec9   28  85289    OH
..                                    ...  ...    ...   ...
295  2ea01d23-cce8-45ee-8698-af6cb3d2bd32   36  32990    NY
296  7efa71b6-9cae-4cf7-87bb-87e8c2f93d77   20  36921    PA
297  cacf1aa1-750e-420c-a105-8ba2bc8e0fca   20  03971    OK
298  17e2cddf-4410-4b02-874c-11fbb2ba77b8   42  75586    MD
299  eff6d601-2803-43e1-8179-96eb11403b3f   30  34908    WY

[300 rows x 4 columns]

In [18]:
# recom_prod = recomendations.merge(products.drop_duplicates('id_product'), on = 'id_product', how= 'left')
# products = products.rename(columns = {'modeild' : 'id_product'})
users = users.rename(columns = {'person_id' : 'id_sender'})
users.head(3)

                              id_sender  age    zip state
0  d0eb7350-ce10-42a2-bab1-cb66319bdfa6   26  76733    WA
1  06ada2a9-ec6e-4306-b83b-33af4489fca0   26  48020    NY
2  acf71426-adca-4f48-87d6-4978dc538448   28  51140    AE

In [19]:
recom_prod2 = recom_prod.merge(users, on = 'id_sender', how = 'left', )
recom_prod2.shape

(7000, 19)

In [20]:
recom_prod2.head(3)

,reco_id,id_sender,id_reciever,id_product,product_bought,year,month,weblabel,brand,catchline,productnature,family,Review-AverageRating,DisplayPrice-Amount,ListPrice-Amount,precio_dif,age,zip,state
0,5dc916dc-6fa3-488f-8ad2-fd14100fa113,5565ac1e-4c2a-4fd8-b990-7a11d594dc0e,13a6c635-2f20-4e22-9e76-c3761d1111be,8605674,1,2008,9,Zapatillas Squash Salming Viper 5 Hombre Amari...,SALMING,"La Viper es una zapatilla rápida, flexible y d...",ZAPATILLAS,ZAPATILLA SQUASH,5.0,79.99,99.99,True,16,39075,IA
1,e9b6a2bb-58d4-4e62-8fda-239da00e42a1,4c1e438a-2b8c-4f84-a22a-869eea346661,84f27bd9-0d26-4f84-b585-cca0e4bbd1d5,8603017,1,1995,17,Camiseta de bádminton manga corta Mujer Perfly...,PERFLY,Primera camiseta por precio pensada para el bá...,CAMISETAS MANGA CORTA,Ropa badminton mujer,4.6,9.99,9.99,False,18,49495,CT
2,91a31be2-e71f-436a-917e-1ac65cc9ef2e,51c3fb8f-c26f-4808-a69a-3f728256cf7a,8c333f9b-af38-4a0c-8bdc-428ffa061312,8763489,1,2002,10,Zapatillas tenis Hombre Revolt Pro 4.0 Negro A...,HEAD,Estas zapatillas de tenis HEAD REVOLT PRO 4.0 ...,ZAPATILLAS,CALZADO HOMBRE MULTICANCHA EXPERTO,5.0,124.99,124.99,False,22,88080,AE

In [21]:
recom_prod2 = recom_prod2.rename(columns = { 'age':  'age_sender', 'zip' :'zip_sender', 'state' :'state_sender' })
recom_prod2.head()

,reco_id,id_sender,id_reciever,id_product,product_bought,year,month,weblabel,brand,catchline,productnature,family,Review-AverageRating,DisplayPrice-Amount,ListPrice-Amount,precio_dif,age_sender,zip_sender,state_sender
0,5dc916dc-6fa3-488f-8ad2-fd14100fa113,5565ac1e-4c2a-4fd8-b990-7a11d594dc0e,13a6c635-2f20-4e22-9e76-c3761d1111be,8605674,1,2008,9,Zapatillas Squash Salming Viper 5 Hombre Amari...,SALMING,"La Viper es una zapatilla rápida, flexible y d...",ZAPATILLAS,ZAPATILLA SQUASH,5.0,79.99,99.99,True,16,39075,IA
1,e9b6a2bb-58d4-4e62-8fda-239da00e42a1,4c1e438a-2b8c-4f84-a22a-869eea346661,84f27bd9-0d26-4f84-b585-cca0e4bbd1d5,8603017,1,1995,17,Camiseta de bádminton manga corta Mujer Perfly...,PERFLY,Primera camiseta por precio pensada para el bá...,CAMISETAS MANGA CORTA,Ropa badminton mujer,4.6,9.99,9.99,False,18,49495,CT
2,91a31be2-e71f-436a-917e-1ac65cc9ef2e,51c3fb8f-c26f-4808-a69a-3f728256cf7a,8c333f9b-af38-4a0c-8bdc-428ffa061312,8763489,1,2002,10,Zapatillas tenis Hombre Revolt Pro 4.0 Negro A...,HEAD,Estas zapatillas de tenis HEAD REVOLT PRO 4.0 ...,ZAPATILLAS,CALZADO HOMBRE MULTICANCHA EXPERTO,5.0,124.99,124.99,False,22,88080,AE
3,b69901f9-c70b-4133-be43-cc6116f1c8fd,45e9a922-e602-4e8f-be77-d6486779ae0f,5f9dfbb7-8bca-494a-802e-f11f12c9906a,8607307,1,2015,31,Zapatillas de pádel Mujer Kuikma PS 990 Dynami...,KUIKMA,Estas zapatillas de pádel te aportarán el dina...,ZAPATILLAS,CALZADO PADEL,4.4,64.99,64.99,False,40,09554,MD
4,0ccdd3e7-a1cb-43fd-814d-a501278c9f9c,250343f4-b757-4c3f-aaea-d7d3ddb14744,34d40a00-18f9-4fa5-9973-ffd5d8663c6f,8372995,1,2001,6,Zapatillas de tenis Mujer TS 100 blanco,ARTENGO,Zapatillas de tenis concebidas para dar los pr...,ZAPATILLAS,CALZADO MUJER MULTICANCHA INIC/PERFECC,4.5,12.99,12.99,False,30,40483,WV

In [22]:
users = users.rename(columns = {'id_sender' : 'id_reciever'})
users.head(3)

                            id_reciever  age    zip state
0  d0eb7350-ce10-42a2-bab1-cb66319bdfa6   26  76733    WA
1  06ada2a9-ec6e-4306-b83b-33af4489fca0   26  48020    NY
2  acf71426-adca-4f48-87d6-4978dc538448   28  51140    AE

In [23]:
recom_prod3 = recom_prod2.merge(users, on = 'id_reciever', how = 'left')
recom_prod3.shape

(7000, 22)

In [26]:
recom_prod3.head(3)

,reco_id,id_sender,id_reciever,id_product,product_bought,year,month,weblabel,brand,catchline,productnature,family,Review-AverageRating,DisplayPrice-Amount,ListPrice-Amount,precio_dif,age_sender,zip_sender,state_sender,age,zip,state
0,5dc916dc-6fa3-488f-8ad2-fd14100fa113,5565ac1e-4c2a-4fd8-b990-7a11d594dc0e,13a6c635-2f20-4e22-9e76-c3761d1111be,8605674,1,2008,9,Zapatillas Squash Salming Viper 5 Hombre Amari...,SALMING,"La Viper es una zapatilla rápida, flexible y d...",ZAPATILLAS,ZAPATILLA SQUASH,5.0,79.99,99.99,True,16,39075,IA,29,82333,NV
1,e9b6a2bb-58d4-4e62-8fda-239da00e42a1,4c1e438a-2b8c-4f84-a22a-869eea346661,84f27bd9-0d26-4f84-b585-cca0e4bbd1d5,8603017,1,1995,17,Camiseta de bádminton manga corta Mujer Perfly...,PERFLY,Primera camiseta por precio pensada para el bá...,CAMISETAS MANGA CORTA,Ropa badminton mujer,4.6,9.99,9.99,False,18,49495,CT,17,99021,GA
2,91a31be2-e71f-436a-917e-1ac65cc9ef2e,51c3fb8f-c26f-4808-a69a-3f728256cf7a,8c333f9b-af38-4a0c-8bdc-428ffa061312,8763489,1,2002,10,Zapatillas tenis Hombre Revolt Pro 4.0 Negro A...,HEAD,Estas zapatillas de tenis HEAD REVOLT PRO 4.0 ...,ZAPATILLAS,CALZADO HOMBRE MULTICANCHA EXPERTO,5.0,124.99,124.99,False,22,88080,AE,19,32799,MN

In [27]:
recom_prod3 = recom_prod3.rename(columns = { 'age':  'age_receiver', 'zip' :'zip_receiver', 'state' :'state_receiver' })
recom_prod3.head()

,reco_id,id_sender,id_reciever,id_product,product_bought,year,month,weblabel,brand,catchline,productnature,family,Review-AverageRating,DisplayPrice-Amount,ListPrice-Amount,precio_dif,age_sender,zip_sender,state_sender,age_receiver,zip_receiver,state_receiver
0,5dc916dc-6fa3-488f-8ad2-fd14100fa113,5565ac1e-4c2a-4fd8-b990-7a11d594dc0e,13a6c635-2f20-4e22-9e76-c3761d1111be,8605674,1,2008,9,Zapatillas Squash Salming Viper 5 Hombre Amari...,SALMING,"La Viper es una zapatilla rápida, flexible y d...",ZAPATILLAS,ZAPATILLA SQUASH,5.0,79.99,99.99,True,16,39075,IA,29,82333,NV
1,e9b6a2bb-58d4-4e62-8fda-239da00e42a1,4c1e438a-2b8c-4f84-a22a-869eea346661,84f27bd9-0d26-4f84-b585-cca0e4bbd1d5,8603017,1,1995,17,Camiseta de bádminton manga corta Mujer Perfly...,PERFLY,Primera camiseta por precio pensada para el bá...,CAMISETAS MANGA CORTA,Ropa badminton mujer,4.6,9.99,9.99,False,18,49495,CT,17,99021,GA
2,91a31be2-e71f-436a-917e-1ac65cc9ef2e,51c3fb8f-c26f-4808-a69a-3f728256cf7a,8c333f9b-af38-4a0c-8bdc-428ffa061312,8763489,1,2002,10,Zapatillas tenis Hombre Revolt Pro 4.0 Negro A...,HEAD,Estas zapatillas de tenis HEAD REVOLT PRO 4.0 ...,ZAPATILLAS,CALZADO HOMBRE MULTICANCHA EXPERTO,5.0,124.99,124.99,False,22,88080,AE,19,32799,MN
3,b69901f9-c70b-4133-be43-cc6116f1c8fd,45e9a922-e602-4e8f-be77-d6486779ae0f,5f9dfbb7-8bca-494a-802e-f11f12c9906a,8607307,1,2015,31,Zapatillas de pádel Mujer Kuikma PS 990 Dynami...,KUIKMA,Estas zapatillas de pádel te aportarán el dina...,ZAPATILLAS,CALZADO PADEL,4.4,64.99,64.99,False,40,09554,MD,19,44228,DC
4,0ccdd3e7-a1cb-43fd-814d-a501278c9f9c,250343f4-b757-4c3f-aaea-d7d3ddb14744,34d40a00-18f9-4fa5-9973-ffd5d8663c6f,8372995,1,2001,6,Zapatillas de tenis Mujer TS 100 blanco,ARTENGO,Zapatillas de tenis concebidas para dar los pr...,ZAPATILLAS,CALZADO MUJER MULTICANCHA INIC/PERFECC,4.5,12.99,12.99,False,30,40483,WV,24,49662,NE

In [28]:
recom_prod3.shape

(7000, 22)

In [30]:
# recom_prod3.to_csv('recom_prod_final.csv', index = False)

In [32]:
recom_prod3.head()

,reco_id,id_sender,id_reciever,id_product,product_bought,year,month,weblabel,brand,catchline,productnature,family,Review-AverageRating,DisplayPrice-Amount,ListPrice-Amount,precio_dif,age_sender,zip_sender,state_sender,age_receiver,zip_receiver,state_receiver
0,5dc916dc-6fa3-488f-8ad2-fd14100fa113,5565ac1e-4c2a-4fd8-b990-7a11d594dc0e,13a6c635-2f20-4e22-9e76-c3761d1111be,8605674,1,2008,9,Zapatillas Squash Salming Viper 5 Hombre Amari...,SALMING,"La Viper es una zapatilla rápida, flexible y d...",ZAPATILLAS,ZAPATILLA SQUASH,5.0,79.99,99.99,True,16,39075,IA,29,82333,NV
1,e9b6a2bb-58d4-4e62-8fda-239da00e42a1,4c1e438a-2b8c-4f84-a22a-869eea346661,84f27bd9-0d26-4f84-b585-cca0e4bbd1d5,8603017,1,1995,17,Camiseta de bádminton manga corta Mujer Perfly...,PERFLY,Primera camiseta por precio pensada para el bá...,CAMISETAS MANGA CORTA,Ropa badminton mujer,4.6,9.99,9.99,False,18,49495,CT,17,99021,GA
2,91a31be2-e71f-436a-917e-1ac65cc9ef2e,51c3fb8f-c26f-4808-a69a-3f728256cf7a,8c333f9b-af38-4a0c-8bdc-428ffa061312,8763489,1,2002,10,Zapatillas tenis Hombre Revolt Pro 4.0 Negro A...,HEAD,Estas zapatillas de tenis HEAD REVOLT PRO 4.0 ...,ZAPATILLAS,CALZADO HOMBRE MULTICANCHA EXPERTO,5.0,124.99,124.99,False,22,88080,AE,19,32799,MN
3,b69901f9-c70b-4133-be43-cc6116f1c8fd,45e9a922-e602-4e8f-be77-d6486779ae0f,5f9dfbb7-8bca-494a-802e-f11f12c9906a,8607307,1,2015,31,Zapatillas de pádel Mujer Kuikma PS 990 Dynami...,KUIKMA,Estas zapatillas de pádel te aportarán el dina...,ZAPATILLAS,CALZADO PADEL,4.4,64.99,64.99,False,40,09554,MD,19,44228,DC
4,0ccdd3e7-a1cb-43fd-814d-a501278c9f9c,250343f4-b757-4c3f-aaea-d7d3ddb14744,34d40a00-18f9-4fa5-9973-ffd5d8663c6f,8372995,1,2001,6,Zapatillas de tenis Mujer TS 100 blanco,ARTENGO,Zapatillas de tenis concebidas para dar los pr...,ZAPATILLAS,CALZADO MUJER MULTICANCHA INIC/PERFECC,4.5,12.99,12.99,False,30,40483,WV,24,49662,NE